### ISSUE TITLE
Support nested html

### ISSUE THREAD

**Issue by ghost** [declandewet/common-tags#160] opened 2018-08-01 15:27 UTC
I've been learning about tagged templates and I discovered common-tags. It's so useful -- many thanks for it!

I was hoping that html might be able to handle nested, multi-line sections, such as you might produce with another html tagged literal. Then you could compose html and have the indenting magically work. But that doesn't seem to be the case.

Here's a test case. Would supporting something like this be at all feasible?

```
const { html } = require("common-tags");

test("renders nested HTML", () => {
  const fruits = ["apple", "banana", "kiwi"];
  const expected = `<!DOCTYPE html>
<html lang="en">
  <body>
    <ul>
      <li>
        <div>apple</div>
      </li>
      <li>
        <div>banana</div>
      </li>
      <li>
        <div>kiwi</div>
      </li>
    </ul>
  </body
</html>`;

  function renderFruit(fruit) {
    return html`
      <li>
        <div>${fruit}</div>
      </li>`;
  }

  const actual = html`
    <!DOCTYPE html>
    <html lang="en">
      <body>
        <ul>
          ${fruits.map(renderFruit)}
        </ul>
      </body>
    </html>`;

  expect(actual).toBe(expected);
});
```

**Comment by fatfisz** [comment] 2018-09-09 01:40
I think it is feasible. Since I've been working today on refurbishing common-tags to improve composability, I might sneak in some other improvements. Sorry for not answering for so long.

**Comment by fatfisz** [comment] 2018-09-09 21:16
The problem is in the `inlineArrayTransformer` part. It's not too difficult to code, but the decisions to be made are hard. Once I wrap my head around this the `html` tag will just work.

**Comment by matthosch** [comment] 2018-10-09 20:08
I'd be interested in this functionality as well. I'm storing some JSX in variables, then interpolating it with template literals. Having the indention work out of the box would be awesome!

**Comment by fatfisz** [comment] 2019-01-20 21:13
I think I managed to do just that. This will be released in the upcoming `next` version.

**Closed by fatfisz** 2019-01-20 21:13 UTC
