### ISSUE TITLE
stripIndent removes trailing new line at end of string

### ISSUE THREAD

**Issue by n1ru4l** [declandewet/common-tags#37] opened 2016-06-04 08:33 UTC
``` javascript
let expectedOutput = stripIndent`
            .foo {
              color: red; }

            .foo {
              color: yellow; }

            .foo {
              color: green; }

            `
```

Output:

``` console
      .foo {\n  color: red; }\n\n.foo {\n  color: yellow; }\n\n.foo {\n  color: green; }
```

Expected Output:

``` console
      .foo {\n  color: red; }\n\n.foo {\n  color: yellow; }\n\n.foo {\n  color: green; }\n
```

My current workaround:

``` javascript
let expectedOutput = stripIndent`
            .foo {
              color: red; }

            .foo {
              color: yellow; }

            .foo {
              color: green; }
            replace
            `
expectedOutput = expectedOutput.replace('replace', '')
```

**Comment by declandewet** [comment] 2016-06-08 09:26
Hi @n1ru4l! This was by design, but I can see why this behaviour would be more useful. Thanks for the suggestion. It'd be a breaking change, so I won't be releasing a fix soon, but in the meantime you can still quickly implement a more "clean" alternative than your workaround:

```js
import {
  TemplateTag,
  stripIndentTransformer,
  replaceResultTransformer } from 'common-tags'

const stripIndent = new TemplateTag(
  stripIndentTransformer,
  {
    onEndResult (endResult) {
      return endResult.trimLeft()
    }
  },
  replaceResultTransformer(/\n{1}(\n*)\s*?$/, '$1')
)

stripIndent`
           .foo {
             color: blue; }

           .foo {
             color: orange; }

           .foo {
             color: red }

           `
```
([Test this code](https://tonicdev.com/declandewet/57575fe4c91caa1300f78dbb))

**Comment by n1ru4l** [comment] 2016-06-08 14:59
Thank you for the code snippet!
Should I close the issue or do you want to keep it open?

**Comment by declandewet** [comment] 2016-06-08 21:17
@n1ru4l You're welcome!

I'd prefer to keep it open for now. :)

**Comment by n1ru4l** [comment] 2016-06-11 07:13
```
trimResultTransformer('left')
```
throws:
`Error: Side not supported: Left`

My workaround is

```javascript
const stripIndent = new TemplateTag(
  stripIndentTransformer,
  replaceResultTransformer(/\n(\n*)\s*?$/, '$1'),
  replaceResultTransformer(/^\n/, '')
)
```

which works fine, I probably could merge those two regex into one but I am a regex noob :P

**Comment by declandewet** [comment] 2016-06-13 09:14
@n1ru4l just upgrade to `common-tags` `1.2.1` and that bug will go away - it was fixed in #39

**Comment by adius** [comment] 2018-02-16 22:44
Damn, this is really unexpected.
Also, it's not documented (you're documentation makes it look like it adds a trailing newline)

Can we please finally fix this?!

**Comment by fatfisz** [comment] 2018-09-08 14:28
I'll add some tests for that and see if this still needs fixing. If so, then I'll work on that.

In the meantime, I'm not too fond of comments full of entitlement. If you don't pay the maintainers to do something, then a) be polite and/or b) submit a fix yourself (this is referring to the comment above, not the previous comments).

**Closed** 2018-09-09 19:41 UTC
Labels: enhancement

**Comment by Enyium** [comment] 2023-12-05 06:09
The rules nicely outlined in the [PR](#165) don't work anymore: Any amount of newlines at the start end end of the string are removed. The fork [proper-tags](https://www.npmjs.com/package/proper-tags) works as desired, however. (I was looking for something that works like [`indoc!`](https://docs.rs/indoc/latest/indoc/#explanation) from the Rust context.)
